# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  test:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.15.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: eslint
          command: npm run lint

#      - run:
#          name: test
#          command: npm run test:coverage

  build_image:
    working_directory: /app

    # use a primary image that already has Docker (recommended)
    docker:
      - image: docker:stable-git

    steps:
      - checkout

      # creates a separate environment for each build for security
      - setup_remote_docker

      - run:
          name: Login into Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - run:
          name: Build the Docker Image
          command: |
            docker build --cache-from=app -t "$DOCKERHUB_REPOSITORY/$CIRCLE_PROJECT_REPONAME:latest" .

      # build and push Docker image
      - run:
          name: Build palantir Docker image
          command: |
            TAG=$CIRCLE_BRANCH-$CIRCLE_BUILD_NUM
            docker tag $DOCKERHUB_REPOSITORY/$CIRCLE_PROJECT_REPONAME:latest $DOCKERHUB_REPOSITORY/$CIRCLE_PROJECT_REPONAME:$TAG
            docker push $DOCKERHUB_REPOSITORY/$CIRCLE_PROJECT_REPONAME

workflows:
  version: 2
  palantir-workflow:
    jobs:
      - test
      - build_image:
          requires:
            - test
          filters:
            branches:
              only: master
